# Generated by Django 4.2.9 on 2024-01-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_side', models.CharField(default='Tail', max_length=4)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
